###
# GET all products 
GET http://localhost:3000/products HTTP/1.1

###
# GET a product by it name
GET http://localhost:3000/products/pomme HTTP/1.1

###
#POST add a new product
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "name": "pomme",
    "quantity": 40
} 

###
#DELETE a product
DELETE http://localhost:3000/products/pomme?quantity=20 HTTP/1.1
